#if !defined(BSP_PINOUT_H_)
#define BSP_PINOUT_H_

#include "hal/gpio.h"
#include "hal/sercom_usart.h"

// TODO: isn't that great that we include it, since it could transitively end up in the app
#include "atsamd21e18a.h"

/** 2-wire hall effect sensor driver pins */
#define MAX9621_INPUT1_PORT PORT_GROUP_A
#define MAX9621_INPUT1_PIN 4
#define MAX9621_INPUT1_PINMUX MUX_PA04A_EIC_EXTINT4
#define MAX9621_INPUT1_EXTINT 4

#define MAX9621_INPUT2_PORT PORT_GROUP_A
#define MAX9621_INPUT2_PIN 5
#define MAX9621_INPUT2_PINMUX MUX_PA05A_EIC_EXTINT5
#define MAX9621_INPUT2_EXTINT 5

#define MAX9621_DIAG1_PORT PORT_GROUP_A
#define MAX9621_DIAG1_PIN 2
#define MAX9621_DIAG1_PINMUX MUX_PA02B_ADC_AIN0
#define MAX9621_DIAG1_EXTINT 2

#define MAX9621_DIAG2_PORT PORT_GROUP_A
#define MAX9621_DIAG2_PIN 3
#define MAX9621_DIAG2_PINMUX MUX_PA03B_ADC_AIN1
#define MAX9621_DIAG2_EXTINT 3

#define MAX9621_SLEEP_PORT PORT_GROUP_A
#define MAX9621_SLEEP_PIN 6

/** BMI088 6-axis IMU pins */
// TODO: PINMUX setup and pad assignment
#define BMI088_ACC_INT_PORT PORT_GROUP_A
#define BMI088_ACC_INT_PIN 14

#define BMI088_GYRO_INT_PORT PORT_GROUP_A
#define BMI088_GYRO_INT_PIN 15

#define BMI088_SPI_MISO_PORT PORT_GROUP_A
#define BMI088_SPI_MISO_PIN 16

#define BMI088_SPI_SCK_PORT PORT_GROUP_A
#define BMI088_SPI_SCK_PIN 17

#define BMI088_SPI_CS_ACC_PORT PORT_GROUP_A
#define BMI088_SPI_CS_ACC_PIN 18

#define BMI088_SPI_MOSI_PORT PORT_GROUP_A
#define BMI088_SPI_MOSI_PIN 19

#define BMI088_SPI_CS_GYRO_PORT PORT_GROUP_A
#define BMI088_SPI_CS_GYRO_PIN 22

/** UART pins */
#define UART_RX_PORT PORT_GROUP_A
#define UART_RX_PIN 9
#define UART_RX_PINMUX MUX_PA09C_SERCOM0_PAD1

#define UART_TX_PORT PORT_GROUP_A
#define UART_TX_PIN 8
#define UART_TX_PINMUX MUX_PA08C_SERCOM0_PAD0

#define UART_CS_PORT PORT_GROUP_A
#define UART_CS_PIN 10

#define UART_TXE_PORT PORT_GROUP_A
#define UART_TXE_PIN 11

#define UART_TX_PAD SERCOM_USART_TX_PAD0
#define UART_RX_PAD SERCOM_USART_RX_PAD1

#endif // BSP_PINOUT_H_
