#if !defined(APP_CONFIG_H_)
#define APP_CONFIG_H_

#define SENSOR_STARTUP_TIME 150
#define ITPMS_STARTUP_TIME 2000

#define SPM_FRONT_CHANNEL 0
#define SPM_REAR_CHANNEL 1

#define SPM_LOW_SPEED_CUTOFF_PERIOD_US 9000000

#endif // APP_CONFIG_H_
