name: Hardware

on:
  pull_request:
    paths:
      - 'hardware/**'
      - '.github/workflows/hardware*.yml'

jobs:
  ERC:
    name: ERC
    runs-on: ubuntu-latest
    container: setsoft/kicad_auto:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run ERC
      working-directory: hardware
      run: ./scripts/run_erc.sh

  DRC:
    name: DRC
    needs: ERC
    runs-on: ubuntu-latest
    container: setsoft/kicad_auto:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run DRC
      working-directory: hardware
      run: ./scripts/run_drc.sh

  documentation:
    name: Export Documents
    needs: DRC
    runs-on: ubuntu-latest
    container: setsoft/kicad_auto
    strategy:
      matrix:
        variant:
          - OPTICAL
          - EXTERNAL
          - HALL
    env:
      VARIANT: ${{ matrix.variant }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # - name: Install KiBot
    #   run: pip3 install git+https://github.com/INTI-CMNB/KiBot.git

    - name: Generate schematic document
      working-directory: hardware
      run: ./scripts/export_schematic.sh

    - name: Generate layout document
      working-directory: hardware
      run: ./scripts/export_layout.sh

    # - name: Generate step file
    #   working-directory: hardware
    #   run: ./scripts/export_step.sh

    - name: Archive Output
      uses: actions/upload-artifact@v2
      with:
        name: documentation-${{ matrix.variant }}
        path: hardware/build/
        if-no-files-found: error

  manufacturing:
    name: Export BOM & Gerbers
    needs: DRC
    runs-on: ubuntu-latest
    container: setsoft/kicad_auto:latest
    strategy:
      matrix:
        variant:
          - OPTICAL
          - EXTERNAL
          - HALL
    env:
      VARIANT: ${{ matrix.variant }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Gerbers
        working-directory: hardware
        run: ./scripts/export_gerbers.sh

      - name: Generate BOM
        working-directory: hardware
        run: ./scripts/export_bom.sh

      - name: Archive Output
        uses: actions/upload-artifact@v2
        with:
          name: manufacturing-${{ matrix.variant }}
          path: hardware/build/
          if-no-files-found: error

  panelize:
    name: Panelize
    needs: DRC
    runs-on: ubuntu-latest
    container: yaqwsx/kikit:v0.7
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Kikit
        run: pip3 install git+https://github.com/yaqwsx/KiKit@d1f7633e1ed87c2ce46e09679d1a1a6a7fb852f5

      - name: Panelize
        working-directory: hardware
        run: kikit panelize -p config/panel.json rotor-sensor.kicad_pcb rotor-sensor-panelized.kicad_pcb

      - name: Archive Output
        uses: actions/upload-artifact@v2
        with:
          name: panelized-board
          path: hardware/rotor-sensor-panelized.kicad_pcb
          if-no-files-found: error

  manufacturing-panelized:
    name: Export Panelized Gerbers
    needs: panelize
    runs-on: ubuntu-latest
    container: setsoft/kicad_auto:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download board
        uses: actions/download-artifact@v2
        with:
          name: panelized-board
          path: hardware

      - name: Generate Gerbers
        working-directory: hardware
        run: kibot -b rotor-sensor-panelized.kicad_pcb -c config/outputs.yaml gerbers

      - name: Archive Output
        uses: actions/upload-artifact@v2
        with:
          name: manufacturing-panelized
          path: hardware/build/
          if-no-files-found: error
