name: Hardware

on:
  pull_request:
    paths:
      - 'hardware/**'
      - '.github/workflows/hardware*.yml'

jobs:
  ERC:
    name: ERC
    runs-on: ubuntu-latest
    container: setsoft/kicad_auto
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run ERC
      working-directory: hardware
      run: ./scripts/run_erc.sh

  DRC:
    name: DRC
    needs: ERC
    runs-on: ubuntu-latest
    container: setsoft/kicad_auto
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run DRC
      working-directory: hardware
      run: ./scripts/run_drc.sh

  documentation:
    name: Export Schematic & Layout
    needs: ERC
    runs-on: ubuntu-latest
    container: setsoft/kicad_auto
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Generate schematic document
      working-directory: hardware
      run: ./scripts/export_schematic.sh

    - name: Archive schematic
      uses: actions/upload-artifact@v2
      with:
        name: schematic
        path: hardware/build/schematic.pdf
        if-no-files-found: error

    - name: Generate layout document
      working-directory: hardware
      run: ./scripts/export_layout.sh

    - name: Archive layout
      uses: actions/upload-artifact@v2
      with:
        name: layout
        path: hardware/build/layout.pdf
        if-no-files-found: error

  render:
    name: Render
    needs: ERC
    runs-on: ubuntu-latest
    container: setsoft/kicad_auto
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Step file
        working-directory: hardware
        run: ./scripts/export_step.sh

      - name: Archive Step file
        uses: actions/upload-artifact@v2
        with:
          name: model
          path: hardware/build/pcb.step
          if-no-files-found: error

  manufacturing:
    name: Export Gerbers & BOM
    needs: DRC
    runs-on: ubuntu-latest
    container: setsoft/kicad_auto
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Gerbers
        working-directory: hardware
        run: ./scripts/export_gerbers.sh

      - name: Archive Gerbers
        uses: actions/upload-artifact@v2
        with:
          name: gerbers
          path: hardware/build/gerbers
          if-no-files-found: error

      - name: Generate BOM
        working-directory: hardware
        run: ./scripts/export_bom.sh

      - name: Archive BOM
        uses: actions/upload-artifact@v2
        with:
          name: bom
          path: hardware/build/bom/*.csv
          if-no-files-found: error
