name: Software

on:
  pull_request:
    paths:
      - '.github/workflows/software*.yml'
      - 'software/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/c4deszes/avr-gcc-docker:v1.1.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: GCC Problem Matcher
        uses: ammaraskar/gcc-problem-matcher@0.1

      - name: Configure build
        working-directory: software
        run: |
          cmake --preset=avr-release-unix .
          
      - name: Print config
        working-directory: software
        run: cat build/avr-release-unix/compile_commands.json

      - name: Build application
        working-directory: software
        run: |
          cmake --build --preset=build-default-avr-release
