name: Software

on:
  pull_request:
    paths:
      - '.github/workflows/software*.yml'
      - 'software/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/c4deszes/arm-gcc-docker:v1.3.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Checkout (line-protocol)
        uses: actions/checkout@v4
        with:
          repository: c4deszes/bike-line-protocol
          path: line-protocol

      - name: Setup line-protocol
        working-directory: line-protocol/python-lib
        run: python -m pip install -e .[dev]

      - name: Checkout (bike-uds-tool)
        uses: actions/checkout@v4
        with:
          repository: c4deszes/bike-uds-tool
          path: bike-uds-tool

      - name: Setup bike-uds-tool
        working-directory: bike-uds-tool/python-lib
        run: python -m pip install -e .[dev]

      - name: GCC Problem Matcher
        uses: ammaraskar/gcc-problem-matcher@0.3.0

      - name: Configure build
        working-directory: software
        run: |
          cmake --preset=armgcc-release-unix .

      - name: Build application
        working-directory: software
        run: |
          cmake --build --preset=build-app-unix
