name: Software

on:
  pull_request:
    paths:
      - '.github/workflows/software*.yml'
      - 'software/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/c4deszes/avr-gcc-docker:v1.2.1
    strategy:
      matrix:
        build_type: [release, debug]
        sensor_profile:
          - 'internal-optical-digital'
          - 'development-digital'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: GCC Problem Matcher
        uses: ammaraskar/gcc-problem-matcher@0.1

      - name: Configure build
        working-directory: software
        run: |
          cmake -DROTOR_SENSOR_PROFILE=${{ matrix.sensor_profile }} --preset=avr-${{ matrix.build_type }} .

      - name: Build application
        working-directory: software
        run: |
          cmake --build --preset=build-${{ matrix.build_type }}
