name: System

on:
  pull_request:
    paths:
      - '.github/workflows/system*.yml'
      - 'system/**'
      
jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        working-directory: system
        run: python -m pip install -r docs/requirements.txt
      
      - name: Intall draw.io dependencies
        run: |
          wget -O drawio.deb https://github.com/jgraph/drawio-desktop/releases/download/v20.6.2/drawio-amd64-20.6.2.deb
          sudo apt install xvfb ./drawio.deb
        
      - name: Build documentation
        working-directory: system
        run: python -m sphinx -b html -E docs docs/_build
        
      - name: Archive documentation
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: |
            system/docs/_build
          if-no-files-found: error
